# In Travis extablish the following environment variables
# DEPLOY_TOKEN
# GITHUB_REPO
# EMAIL
# USERNAME

language: ruby
rvm:
- 2.3.1

before_install:
  - gem update --system
  - gem --version


before_script:
  - chmod +x ./script/cibuild
  - git config diff.renameLimit 999999
  - cp docs/guides/contributing.md .github/CONTRIBUTING.md
  - cp about/code-of-conduct.md .github/CODE_OF_CONDUCT.md

deploy:
  provider: pages
  skip_cleanup: true

script: ./script/cibuild

env:
  global:
  - GITHUB_REPO: github.com/100ideas/sphere.git
  - DEPLOY_BRANCH: gh-pages
  - SOURCE_BRANCH: responsive-deploy
  - JEKYLL_ENV: production


exclude: [vendor]

sudo: false
