# Site settings
title: DIYbiosphere
description: "A collaborative library of Do-it-Yourself Biology initiatives"
baseurl: "" # the subpath of your site, e.g. /blog
url: "sphere.diybio.org"
permalink: /updates/:year/:month/:day/:title
repository: DIYbiosphere/sphere
github_username: DIYbiosphere
twitter:
  username: DIYbiosphere


# Excluded files and dirs
exclude: ['vendor', 'script', 'Gemfile', 'Gemfile.lock', 'README.md', 'DataReusePlan.txt', '.assets-cache', '.sass-cache', 'node_modules']

github_comments_repository:  diybiosphere/talk

# Build settings
markdown: kramdown
highlighter: rouge

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-github-metadata
  - jekyll-git_metadata
  - algoliasearch-jekyll
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-avatar
  - jekyll-toc #https://github.com/toshimaru/jekyll-toc/
  - jekyll-timeago
  - jekyll-giphy
  - geocoder

# Collections
collections:
  projects:
    title: Projects
    output: true
    permalink: /entries/:collection/:path
    collection: Project
  startups:
    title: Startups
    output: true
    permalink: /entries/:collection/:path
    collection: Startup
  labs:
    title: Labs
    output: true
    permalink: /entries/:collection/:path
    collection: Lab
  incubators:
    title: Incubators
    output: true
    permalink: /entries/:collection/:path
    collection: Incubator
  groups:
    title: Groups
    output: true
    permalink: /entries/:collection/:path
    collection: Group
  networks:
    title: Networks
    output: true
    permalink: /entries/:collection/:path
    collection: Network
  events:
    title: Events
    output: true
    permalink: /entries/:collection/:path
    collection: Event
  others:
    title: Others
    output: true
    permalink: /entries/:collection/:path
    collection: Other

# Default Values
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: projects
    values:
      layout: entry
      permalink: /entries/:collection/:name/
      collection: Project
  -
    scope:
      type: startups
    values:
      layout: entry
      permalink: /entries/:collection/:name/
      collection: Startup
  -
    scope:
      type: labs
    values:
      layout: entry
      permalink: /entries/:collection/:name/
      collection: Lab
  -
    scope:
      type: incubators
    values:
      layout: entry
      permalink: /entries/:collection/:path/
      collection: Incubator
  -
    scope:
      type: groups
    values:
      layout: entry
      permalink: /entries/:collection/:name/
      collection: Group
  -
    scope:
      type: networks
    values:
      layout: entry
      permalink: /entries/:collection/:name/
      collection: Network
  -
    scope:
      type: events
    values:
      layout: entry
      permalink: /entries/:collection/:name/
      collection: Event
  -
    scope:
      type: others
    values:
      layout: entry
      permalink: /entries/:collection/:name/
      collection: Other

# PLUGIN CONFIGURATIONS

# Jekyll assets plugin
assets:
  compress:
    css: sass
    js: uglifier
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  assets:
    - "*.png"
    - "*.gif"
    - "*.jpg"
    - "*.svg"
  sources:
    - _assets
    - _assets/img
    - _assets/js
    - _assets/css
    - _assets/gif

# Jekyll-Tagging: https://github.com/pattex/jekyll-tagging/
tag_page_layout: tag_page
tag_page_dir: tag

# AlgoliaSearch-Jekyll: https://github.com/algolia/algoliasearch-jekyll/
algolia:
  application_id: 'ITI5JHZJM9'
  index_name: 'diybiosphere'
  lazy_update: true
  settings:
    advancedSyntax: true
    distinct: true
    attributeForDistinct: 'url'
    ignorePlurals: true
    attributesToIndex:
      - title
      - city
      - state
      - country
      - unordered(text)
      - unordered(tags)
    ranking:
      - typo
      - geo
      - proximity
      - attribute
      - custom
    attributesForFaceting:
      - collection
      - type-org
      - city
      - state
      - country
      - tags
      - status
    attributesToRetrieve:
      - title
      - collection
      - type-org
      - city
      - state
      - country
      - tags
      - status
      - text
      - motto
      - url
      - start-date
      - end-date
      - host-org
      - last_modified_at
      - timestamp
    attributesToSnippet: ['text:20']
    attributesToHighlight: ['*']
    highlightPostTag: </span>
    highlightPreTag: <span class="search-highlight">
    minWordSizefor1Typo: 3
    minWordSizefor2Typos: 7
