# Site settings
title: DIYbiosphere
email: contact@contact.com
description: "A collaborative database of Do-it-Yourself Biology initiatives"
baseurl: "" # the subpath of your site, e.g. /blog
url: "sphere.diybio.org"
permalink: /news/:year/:month/:day/:title
repository: "DIYbiosphere/sphere"
github_username: "DIYbiosphere"
twitter:
  username: DIYbiosphere


# Excluded files and dirs
exclude: [script, Gemfile, Gemfile.lock, README.md, DataReusePlan.txt]

# Jekyll assets
assets:
  compress: 
    css: sass
    js: uglifier
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

# Build settings
markdown: kramdown

gems:
  - jemoji
  - jekyll-gist
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-github-metadata

# Collections
collections:
  projects:
    title: Projects
    output: true
    permalink: /database/projects/
  startups:
    title: Startups
    output: true
    permalink: /database/startups/
  labs:
    title: Labs
    output: true
    permalink: /database/labs/
  incubators:
    title: Incubators
    output: true
    permalink: /database/incubators/
  groups:
    title: Groups
    output: true
    permalink: /database/groups/
  networks:
    title: Networks
    output: true
    permalink: /database/networks/
  events:
    title: Events
    output: true
    permalink: /database/events/
  others:
    title: Others
    output: true
    permalink: /database/others/

# Default Values
defaults:
  -
    scope:
      path: ''
    values:
      layout: landing
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: projects
    values:
      layout: entry
      permalink: /database/projects/:title
  -
    scope:
      type: startups
    values:
      layout: entry
      permalink: /database/startups/:title
  -
    scope:
      type: labs
    values:
      layout: entry
      permalink: /database/labs/:title
  -
    scope:
      type: incubators
    values:
      layout: entry
      permalink: /database/incubators/:title
  -
    scope:
      type: groups
    values:
      layout: entry
      permalink: /database/groups/:title
  -
    scope:
      type: networks
    values:
      layout: entry
      permalink: /database/networks/:title
  -
    scope:
      type: events
    values:
      layout: entry
      permalink: /events/:title
  -
    scope:
      type: others
    values:
      layout: entry
      permalink: /others/:title
