# Site settings
title: DIYbiosphere
description: "An open source project to connect DIYBio Initiatives from all over the world"
baseurl: "" # the subpath of your site, e.g. /blog
url: "sphere.diybio.org"
repository: diybiosphere/sphere
comments_repo:  diybiosphere/talk
permalink: /:path/
twitter:
  username: DIYbiosphere


# Excluded files and dirs
exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - DataReusePlan.txt
  - .assets-cache
  - .sass-cache
  - node_modules
  - semantic.json
  - package-lock.json
  - package.json

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false

# Where things are
destination:  _site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes


plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-last-modified-at
  - jekyll-toc #https://github.com/toshimaru/jekyll-toc/

# Collections
collections:
  projects:
    title: Projects
    output: true
    collection: Project
  startups:
    title: Startups
    output: true
    collection: Startup
  labs:
    title: Labs
    output: true
    collection: Lab
  incubators:
    title: Incubators
    output: true
    collection: Incubator
  groups:
    title: Groups
    output: true
    collection: Group
  networks:
    title: Networks
    output: true
    collection: Network
  events:
    title: Events
    output: true
    collection: Event
  others:
    title: Others
    output: true
    collection: Other

# Default Values
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: projects
    values:
      layout: entry
      collection: Project
      permalink: /:collection/:name/
  -
    scope:
      type: startups
    values:
      layout: entry
      collection: Startup
      permalink: /:collection/:name/
  -
    scope:
      type: labs
    values:
      layout: entry
      collection: Lab
      permalink: /:collection/:name/
  -
    scope:
      type: incubators
    values:
      layout: entry
      collection: Incubator
      permalink: /:collection/:name/
  -
    scope:
      type: groups
    values:
      layout: entry
      collection: Group
      permalink: /:collection/:name/
  -
    scope:
      type: networks
    values:
      layout: entry
      collection: Network
      permalink: /:collection/:name/
  -
    scope:
      type: events
    values:
      layout: entry
      collection: Event
      permalink: /:collection/:name/
  -
    scope:
      type: others
    values:
      layout: entry
      collection: Other
      permalink: /:collection/:name/
  -
    scope:
      type: pages
    values:
      layout: page


sass:
  sass_dir: assets/css
  style: compressed

# AlgoliaSearch-Jekyll: https://github.com/algolia/algoliasearch-jekyll/
algolia:
  application_id: 'ITI5JHZJM9'
  index_name: 'diybiosphere'
  search_only_api_key: 'b427318cf6d881e5d3ffd84adf39219e'
  indexing_batch_size: 100
  nodes_to_index: 'p,blockquote,li'
  files_to_exclude:
    - index.html
    - 404.html
    - browse.html
    - README.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - about/*.md
    - about/*/*.md
    - docs/*.md
    - docs/*/*.md
    - docs/*/*/*.md
    - docs/*/*/*.md
  settings:
    ranking:
      - typo
      - proximity
      - attribute
      - custom
    customRanking:
      - asc(title)
    searchableAttributes:
      - title
      - subtitle
      - hosts
      - hostsSentence
      - partners
      - partnersSentence
      - city
      - state
      - country
      - content
      - tags
      - collection
      - predecessor
      - successor
      - timestamp
      - last_modified_at
      - _geoloc
      - status
    attributesToRetrieve:
      - title
      - subtitle
      - url
      - type-org
      - uberimage
      - hosts
      - hostsSentence
      - partners
      - partnersSentence
      - city
      - state
      - country
      - content
      - tags
      - tagsExist
      - collection
      - start-date
      - end-date
      - predecessor
      - successor
      - status
      - project
      - lab
      - group
      - network
      - startup
      - incubator
      - event
      - other
      - last_modified_at
      - timestamp
      - _geoloc
      - status
    attributesForFaceting:
      - collection
      - type-org
      - city
      - state
      - country
      - tags
      - status
      - start-date
      - end-date
      - status
    attributesToHighlight:
      - title
      - subtitle
      - hosts
      - hostsSentence
      - partners
      - partnersSentence
      - city
      - state
      - country
      - content
      - tags
      - collection
      - predecessor
      - successor
      - status
    attributesToSnippet: ['content:10']
    highlightPreTag: <span class="search-highlight">
    highlightPostTag: </span>
